### ISSUE TITLE
Illegal address in string ``'' when sharing portfolio

### ISSUE THREAD

**Issue by smkeesle** [karutaproject/karuta-backend#44]
![screen shot 2016-08-26 at 6 06 47 pm](https://cloud.githubusercontent.com/assets/342735/18022548/cd373140-6bbd-11e6-9abc-2ece75054b43.png)
This is what I see in the log when I try to share a portfolio with someone by putting in an email address (there are no extra spaces or punctuation in the entered email address):

Versions
Application : 1.0 (2016-04-29)
Karuta-frontend : 2.1.2 (2016-07-18)
Karuta-backend : 2.0.0.7 (2016-07-18)
Karuta-fileserver : 1.2.0.1 (2015-11-12)
​

==> apache-tomcat/logs/catalina.out <==
javax.mail.internet.AddressException: Illegal address in string ``''
at javax.mail.internet.InternetAddress.<init>(InternetAddress.java:114)
at com.portfolio.data.utils.MailUtils.postMail(MailUtils.java:95)
at com.portfolio.data.attachment.MailService.doPost(MailService.java:166)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:676)
at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1502)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1458)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:745)

**Comment by nobry** [comment]
mail_login has to be defined, it's the sender's email.
I have added some comment about it in the configuration file
https://github.com/karutaproject/karuta-backend/commit/d0fa2a4c84e85a9f0c610bca6bfdc98a14b35af0
