### ISSUE TITLE
MailService fails when SMTP credentials are commented in the configuration file

### ISSUE THREAD

**Issue by eviweb** [karutaproject/karuta-backend#65]
Hi @nobry,

the `MailService` fails when in the `configKaruta.properties` file, `mail_login` is commented.
The error message is:
```
at javax.mail.internet.InternetAddress.parse(InternetAddress.java:678)
        at javax.mail.internet.InternetAddress.parse(InternetAddress.java:638)
        at javax.mail.internet.InternetAddress.<init>(InternetAddress.java:111)
        at com.portfolio.data.utils.MailUtils.postMail(MailUtils.java:95)
        at com.portfolio.data.attachment.MailService.doPost(MailService.java:166)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1504)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1460)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
09:54:33.780 [http-nio-8080-exec-54] ERROR com.portfolio.data.attachment.MailService - null
```
The problem comes from the `MailUtils.postMail` at the line `String mail_login = ConfigUtils.get("mail_login");` where `ConfigUtils.get("mail_login");` returns `null`.

As `mail_login` and `mail_password` are commented by default in the configuration file, we expect `MailUtils.postMail` to handle this case.

Best regards

Eric

**Comment by eviweb** [comment]
In fact it seems, that `mail_login` and `mail_password` cannot be empty.

**Comment by nobry** [comment]
Usually this service is used. But I guess if someone doesn't need it, they should be able to comment it.
I'll make some change

**Comment by nobry** [comment]
It should be good in https://github.com/karutaproject/karuta-backend/commit/e8c9bbd568fec21c54b0ca2aeceee9a65c361fc5
If either the username or password is not defined, sending a message will be ignored
If the notification configuration line is commented, the service doesn't try anything.

**Comment by eviweb** [comment]
Hi @nobry,
thanks for your quick response.
However the problem on our side is that our SMTP server does not need credentials which currently prevents the use of the `SendMail` feature.
In fact this is not truly what we expect...
IMHO, if notification is enabled we expect that the mail service works with the configuration we give to it, not that this service guesses what are correct settings as long as an SMTP server address is provided.
Regarding other SMTP settings, if they come to lack in the configuration file, common defaults should be used instead (ie. _port_ `25`, starttls to `false`...). 
best regards
Eric

**Comment by nobry** [comment]
Hello,
I'm curious about how does the email server know which email it should allow to go through? Is it a kind of open relay server with limited IP address access?
Our regular use case is having Karuta use an email account. Most configuration for it is in the configKaruta.properties file, and that the email server is using SSL connection. But it should still work if you use set it to use the regular SMTP port, with an email account though.

**Comment by nobry** [comment]
Sorry for the delay, I set up a local postfix and it seems to work without login. 
The commit is at https://github.com/karutaproject/karuta-backend/commit/2ace0ad2a5ce0d4882fa4ba131f83ac7d5e699b3 and I'll merge it if it's good.

When sending the email, mail_login is used as the sender and the sender specified in the email is used as CC. I don't know if this behavior suits you and there might be changes to be made if it doesn't.

You still need to change a bit configKaruta.properties:
`# mail_login is also used as the sender`
`mail_login=USERNAME@gmail.com`
`# mail_password can be commented, is ignored if useauth is false`
`# mail_password=PASSWORD`
`smtp.server={your_server}`
`smtp.port=25`
`smtp.useauth=false`
`# set as false is another port than the SSL one is used`
`smtp.starttls=false`

**Comment by eviweb** [comment]
Hi @nobry,

thanks for this update, I will give it a try.
I also want to apologize, regarding my latency, but I wanted to get more information on how our SMTP server works.
So, it is an internal SMTP which filters senders' IP addresses.
I know that similar institutions as mine also use this type of configuration.
What I didn't grasp the first time I looked at this issue is that the `mail_login` setting is used as the sender address.
Personally I expected that the email of the account that sends the email was used as the sender address and not be used as CC.
This is typically how work the other applications we use.
This permits the recipient of the email to reply to the sender simply by using his email client `Reply` button.
IMHO, this is grandly more comfortable in terms of usage than having to think about not to forget to use the `Reply to all` button.

In any case, many thanks for you reactivity,

best regards

Eric

**Comment by eviweb** [comment]
Hi @nobry,
as a workaround using a fake email address like `no-reply@domain.tld` resolves the issue, but with the original version of the `MailUtils` the one of the [master branch](https://github.com/karutaproject/karuta-backend/blob/master/src/com/portfolio/data/utils/MailUtils.java).
Last changes prevent this.
Eric

**Comment by nobry** [comment]
Hi Eric,
Yes, using a no-reply email is the usual behavior when the backend was coded, since the system is sending messages rather than just relaying it.
I'll delete the test branch since it didn't work out. If you think it's resolved (sort of), you can close the issue.

**Comment by eviweb** [comment]
Hi @nobry,
I think the decision to close this issue is more on your side.
It depends on the evolution you want to give to this feature and if you want to address the use case described above.
Personally, I think this issue may stay opened as a kind of reminder.
The behaviour I tried to describe is the default one that some institutions like mine expect to get when using an application that permits people to deal with emails.
Best regards
Eric

**Comment by nobry** [comment]
That issue was brought up enough time and should be fixed from this point onward
https://github.com/karutaproject/karuta-backend/commit/d9a5cccb002538450e2fc895efb684d83f6ff8d0

Setting "smtp.useauth" as false in configKaruta.properties skip sending authentication, thus allowing passwordless messages to be sent in internal network.

Thank you for your patience.
