### ISSUE TITLE
User cannot upload image to ImageBlock

### ISSUE THREAD

**Issue by eviweb** [karutaproject/karuta-backend#66]
Hi,
the owner of a Portfolio with permissions to read/write/delete on an `ImageBlock` resource, cannot upload images while it works correctly with an `Image` resource.
It results in an HTTP error 403: _No WRITE credential_ thrown in `MysqlDataProvider.putResource()`
Eric

**Comment by olivier-gerbe** [comment]
Hi Eric,
Roles were missing in `ImageBlock`. I added them in `Templates/BlockElements`. I you want correct your portfolio model, follow the instructions on `Templates/BlockElements` to set them to `student etudiant`

**Comment by eviweb** [comment]
Hi @olivier-gerbe,
in fact we didn't work with `student etudiant` role but with a more generic `author`one.
I had imported the `Templates/BlockElements` and tweak the metadata to match our needs.
Here follow the metadata:
- semantic tag: `imgblck-author`
- Roles - See: `author`
- Roles - Delete: `author`
- Roles - Edit Resource: `author`
- Roles - Edit Label: `author`
- Roles - Duplicate: `author`
- Roles - Move: `author`
- Roles - Show/Hide: `author`
- Roles - Show To: `all supervisor`

The use case is that an `author`, from his/her portfolio, can add an image block through a custom menu.
The image block is correctly imported but I get immediately a 404 error from the `GET /karuta-backend/resources/resource/file/` API.
The related server log extract:
```
CACHE HIT FOR CODE: reflexpro.blocks-components -> 9756882b-0ce5-491c-aae3-58fa0518f4bb
FileServlet::doGet: /f4b835c2-4b58-11e7-89e3-00163ecaaeb5 from user: 18
```
Then, when I try to add an image I get a 403 error from the `POST karuta-backend/resources/resource/file/` API with the following response body:
```html
<!DOCTYPE html><html><head><title>Apache Tomcat/8.0.32 (Ubuntu) - Error report</title><style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}.line {height: 1px; background-color: #525D76; border: none;}</style> </head><body><h1>HTTP Status 403 - </h1><div class="line"></div><p><b>type</b> Status report</p><p><b>message</b> <u></u></p><p><b>description</b> <u>Access to the specified resource has been forbidden.</u></p><hr class="line"><h3>Apache Tomcat/8.0.32 (Ubuntu)</h3></body></html>
```
The related server log extract:
```
08:13:00.595 [http-nio-8080-exec-11] ERROR com.portfolio.data.attachment.FileServlet - Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
Jun 07, 2017 8:13:00 AM sun.net.www.protocol.http.HttpURLConnection writeRequests
FINE: sun.net.www.MessageHeader@4762c20a17 pairs: {POST /karuta-fileserver/ HTTP/1.1: null}{app: /karuta-backend}{pragma: no-cache}{cache-control: no-cache}{user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36}{content-type: application/octet-stream}{accept: application/json, text/javascript, */*; q=0.01}{x-requested-with: XMLHttpRequest}{referer: http://karuta-dev.lxd/karuta/application/htm/karuta.htm}{accept-encoding: gzip, deflate}{accept-language: en-US,en;q=0.8}{cookie: JSESSIONID=F7C3D72BC7F76E0000A74B40DD0A5188; karuta-language=fr}{x-forwarded-for: 10.5.219.45}{filename: f4b835c2-4b58-11e7-89e3-00163ecaaeb5}{Host: localhost:8080}{Connection: keep-alive}{Content-Length: 30891}
3276177 [http-nio-8080-exec-6] INFO ca.mati.portfolio.fileserveur.PersistenceConfig - Persistence location: /var/lib/tomcat8/karuta-fileserver_config/persistence_config.properties
Receiving data...
Data received.
File written to: /var/lib/tomcat8/karuta-fileserver_data/karuta-backend/3aba0bd2-811e-43dd-b14a-27d7c2cabc82
Jun 07, 2017 8:13:00 AM sun.net.www.protocol.http.HttpURLConnection getInputStream0
FINE: sun.net.www.MessageHeader@6e691d194 pairs: {null: HTTP/1.1 200 OK}{Server: Apache-Coyote/1.1}{Content-Length: 36}{Date: Wed, 07 Jun 2017 08:13:00 GMT}
```
As we can see, the file is correctly uploaded under `/var/lib/tomcat8/karuta-fileserver_data/karuta-backend/`, I checked it, and it is.

Moreover, when I try to change the coverage setting, I get a 403 error from the `PUT rest/api/resources/resource/` API with the following response body: `No WRITE credential`.
A popup message warns me: `Error in UpdateResource : No WRITE credential`.
This generates the following log:
```
no warnings or errors were found
08:23:04.628 [http-nio-8080-exec-13] ERROR com.portfolio.rest.RestServicePortfolio - null
08:23:04.628 [http-nio-8080-exec-13] ERROR com.portfolio.rest.RestServicePortfolio - null
com.portfolio.rest.RestWebApplicationException
        at com.portfolio.data.provider.MysqlDataProvider.putResource(MysqlDataProvider.java:8139)
        at com.portfolio.rest.RestServicePortfolio.putResource(RestServicePortfolio.java:3608)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$TypeOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:185)
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1504)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1460)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
Jun 07, 2017 8:23:04 AM com.sun.jersey.spi.container.ContainerResponse logException
FINE: Mapped exception to response: 403 (Forbidden)
com.portfolio.rest.RestWebApplicationException
        at com.portfolio.data.provider.MysqlDataProvider.putResource(MysqlDataProvider.java:8139)
        at com.portfolio.rest.RestServicePortfolio.putResource(RestServicePortfolio.java:3608)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$TypeOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:185)
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1504)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1460)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
```
This component is configured as other block components with which I don't have any problem (ie. Document).

Could this issue come from the Tomcat environment configuration or is it more internal to Karuta ?

For my own culture, why are there two different resource API entry points:
- `/karuta-backend/resources/`
- `/karuta-backend/rest/api/resources/`

I also gave a try with the updated `Templates/BlockElements` after having changed the roles to `author` with the same result.

Thanks for your help

Eric

**Comment by eviweb** [comment]
Solved by editing each component metadata for the image block as described here: https://github.com/karutaproject/karuta-templates/blob/master/Blocks-Components/README.md
thanks @olivier-gerbe
